### <span id="0">Computer-exam BFVM23DATASC5 - Supervised Learning</span>

# 2024-2025 - first opportunity, Mon. 04 Nov 2025, 12:30-16:30, ZP11/H1.86

Take a minute to read the following instructions and information.

## Materials

On BlackBoard you will find a zip-file containing the following materials:

* this exam `BFVM23DATASC5_T_DataScience5_SupervisedLearning_2425_DSLS_KRPE-LADR.ipynb` (also as `*.pdf`);
* data files:
  * `cheminformatics_data.csv`
  * `codebook.csv`

## Instructions

This is an open book exam that you take on school workstations using your own account. You are allowed to use any materials in your home folder, look up information on the internet, as well as consult any written materials. However, you are **not** allowed to utilize your own devices (e.g. telephone or laptop) or use online communication media or AI-tools (e.g. chat and ChatGPT); this will be considered fraud. You are allowed to leave the room for toilet or coffee breaks, except during the first and last hour of the scheduled exam time. You are not permitted to confer with fellow students about code.

This exam consists of the following parts:

1. **<a href="#1">Part I</a>**

2. **<a href="#2">Part II</a>**

3. **<a href="#3">Part III</a>**

4. **<a href="#4">Part IV</a>**

Each part directs you to perform a particular supervised-machine learning analysis. If you do not understand what is meant, you may ask the exam's supervisor for clarification. Execute the analysis that is requested, and use your own judgement to perform any steps that you deem necessary. **Do not only provide code solutions, but explain by means of comments and/or text markup why you perform steps, as well as what you conclude from the output of an analysis!**

The various parts can be answered separately; if you are unable to (fully) solve one part, an explanation of your intended solution in the form of text or pseudo-code may be awarded partial credit. You can always continue to a next part. Save your notebook regularly to avoid inadvertent loss of your progress!

## Assessment

All parts have the possible number of points to be scored indicated above. Your grade will be calculated as follows:

$$
\text{Grade} = 1 + 9 \cdot \frac {\text{Points Scored}} {\text{Maximum Score}}
$$

* 40 % of your grade is based on the insightfulness of provided explanations, motivations, interpretations, and conclusions drawn from your analyses.

* 40 % of your grade is based on the correctness, completeness, efficiency, and intelligibility of the code(*) that you produce.

* 20 % of your grade is based on whether or not you use your own classes, developed during the course.


Instructions on how to submit your answers after you finish are provided at the very <a href="#X">bottom</a>.

***

## Data

For a series of almost 1700 molecules their activity against a human Glucocorticoid receptor was measures as IC50 concentrations (in nM). This is the concentration at which the compound is still 50% effective, so lower is more potent. 
For each of these molecules 201 features were derived from their chemical structure. In addition, for each molecule a 1024 bit fingerprint was calculated resulting in, in total, 1225 features per molecule.

The dataset contains 3 targets you will be predicting:
1) The IC50 value (`standard_value`)
2) Whether the IC50 value is < 1000 nM (`is_active`)
3) Whether the molecule satisfies Lipinski's "rule of 5" (`lipinski`)

The codebook describes for each column in the data (`variable`) what it contains (`label`), the units (`units`), what type of variable it is (`type`), and a reference where you can find more information about the feature (`reference`). All of these are provided at a "best effort"-basis; the codebook is incomplete and could be wrong in places... Some of the features are easy to interpret, others are more abstract. All fingerprint features are booleans. The feature names are formatted as `fp{idx}` with `idx` running from `0` to `1024` (non inclusive) and are omitted from the codebook.

The `type` can have 4 values:
- nominal: for nominal variables
- ratio: for ratio variables
- bool: for boolean variables
- count: for variables with non-negative integer values

For more information on the features, see the codebook and/or https://deepmol.readthedocs.io/en/stable/deepmol_docs/featurization.html#d-1d-and-2d-descriptors. For more information on the fingerprints, see https://www.rdkit.org/docs/GettingStartedInPython.html#feature-definitions-used-in-the-morgan-fingerprints and/or https://dx.doi.org/10.1021/ci100050t

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('cheminformatics_data.csv')
codebook = pd.read_csv('codebook.csv', index_col=False)

In [3]:
data

,molecule_chembl_id,standard_value,lipinski,is_active,canonical_smiles,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,...,fp1014,fp1015,fp1016,fp1017,fp1018,fp1019,fp1020,fp1021,fp1022,fp1023
0,CHEMBL134277,100.0,False,True,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccsc1)Oc1ccc(...,15.158941,15.158941,0.277125,-3.859397,0.481256,...,1,0,0,0,0,0,0,0,0,0
1,CHEMBL415524,77.0,False,True,CCc1ccccc1/C=C1\Oc2ccc(F)cc2-c2ccc3c(c21)C(C)=...,15.415673,15.415673,0.407112,-3.996804,0.469857,...,1,0,0,0,0,0,0,0,0,0
2,CHEMBL336353,320.0,False,True,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccccc1N(C)C)O...,15.467937,15.467937,0.423251,-4.017487,0.474812,...,1,0,0,0,0,0,0,0,0,0
3,CHEMBL413309,250.0,False,True,CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccccc1)Oc1c(F...,15.763427,15.763427,0.326528,-3.909144,0.488806,...,1,0,0,0,0,0,0,0,0,0
4,CHEMBL717,10.0,True,True,CC(=O)O[C@]1(C(C)=O)CC[C@H]2[C@@H]3C[C@H](C)C4...,14.561580,14.561580,2.545120,-6.060854,0.647973,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1684,CHEMBL5282323,6960.0,False,False,COc1cc(C)c(Cl)cc1S(=O)(=O)Nc1ccc2c(c1)CCCN2C(=...,14.344989,14.344989,0.429853,-6.079389,0.535937,...,0,0,0,0,0,0,0,1,0,0
1685,CHEMBL5266323,2070.0,False,False,COc1cc(C)c(Cl)cc1S(=O)(=O)Nc1ccc2c(c1)CCCN2C(=...,14.088936,14.088936,0.350488,-6.056378,0.482584,...,0,0,0,0,0,0,0,0,0,0
1686,CHEMBL5269021,2220.0,False,False,COc1cc(C)c(Cl)cc1S(=O)(=O)Nc1ccc2c(c1)CCCN2C(=...,14.090200,14.090200,0.573348,-6.147867,0.427672,...,0,0,0,0,0,1,0,0,0,0
1687,CHEMBL5272312,3430.0,False,False,COc1ccc(C(=O)N2CCCc3cc(NS(=O)(=O)c4cc(Cl)c(C)c...,14.499154,14.499154,0.521061,-6.162963,0.458223,...,0,0,0,0,0,0,0,0,0,0
1688,CHEMBL5267245,1860.0,True,False,C#CC1=C(SCC(=O)c2ccccc2)NC(C)=C(C(C)=O)C1c1cccs1,13.469477,13.469477,0.170037,-3.678839,0.567787,...,0,0,0,1,0,1,0,0,0,0

In [4]:
codebook

,variable,label,units,type,reference
0,molecule_chembl_id,Molecule identifier,NaN,nominal,NaN
1,standard_value,IC50 activity against Glucocorticoid receptor,nM,ratio,NaN
2,lipinski,Whether the molecule satisfies Lipinski's rule...,NaN,bool,NaN
3,is_active,Whether the standard_value is less than 1000 nM,NaN,bool,NaN
4,canonical_smiles,A SMILES string representing the molecule,NaN,nominal,NaN
...,...,...,...,...,...
201,fr_thiazole,Number of thiazole rings,NaN,count,NaN
202,fr_thiocyan,Number of thiocyanates,NaN,count,NaN
203,fr_thiophene,Number of thiophene rings,NaN,count,NaN
204,fr_unbrch_alkane,Number of unbranched alkanes of at least 4 mem...,NaN,count,NaN
205,fr_urea,Number of urea groups,NaN,count,NaN

In [5]:
TARGETS = ['standard_value', 'lipinski', 'is_active']
IDENTIFIERS = ['molecule_chembl_id', 'canonical_smiles']
FINGERPRINT_COLUMNS = [f'fp{idx}' for idx in range(1024)]
FEATURE_COLUMNS = [c for c in codebook['variable'] if c not in TARGETS+IDENTIFIERS]

<a id="1" href="#0" style="text-align: right; display: block;">Back to top</a>

## Part I

In this part you will predict the `is_active` target, and see how informative the fingerprint is. **In all following questions, explain why you perform steps, why you picked specific models, as well as what you conclude from the output.**

1) Train and validate a model to predict the `is_active` column using the columns in `FEATURE_COLUMNS` (or a subset thereof)
2) Train and validate a model to predict the `is_active` column using the columns in `FINGERPRINT_COLUMNS` (or a subset thereof)
3) Train and validate a model to predict the `is_active` column using the columns in both `FEATURE_COLUMNS` and `FINGERPRINT_COLUMNS` (or a subset thereof)
4) Is fingerprinting useful?

In [6]:
# YOUR ANSWER GOES HERE

<a id="2" href="#0" style="text-align: right; display: block;">Back to top</a>

## Part II

In this part you will predict the `lipinski` target. This column is actually derived from 4 columns in `FEATURE_COLUMNS` (`NumHDonors`, `NumHAcceptors`, `MolWt`, and `MolLogP`). Each of these columns was compared to a threshold, and if all 4 features were less than their threshold the molecule satisfies the Lipinski rule-of-5. 
**In all following questions, explain why you perform steps, why you picked specific models, as well as what you conclude from the output.**

1) What kind of model could reproduce this behaviour?
2) Train and validate such a model to find the used threshold values.
3) Train and validate a model to predict the `lipinski` column using the columns in `FEATURE_COLUMNS`, *except* `NumHDonors`, `NumHAcceptors`, `MolWt`, and `MolLogP`. Can you say something about which features are most important now?
3) Train and validate a model to predict the `lipinski` column using the columns in `FINGERPRINT_COLUMNS`

In [7]:
# YOUR ANSWER GOES HERE

<a id="3" href="#0" style="text-align: right; display: block;">Back to top</a>

## Part III

Quite a few of the features are counts, which are usually distinctly not normally distributed. Instead, their likelihoods can be modelled using the Gamma distribution (https://en.wikipedia.org/wiki/Gamma_distribution):
$$
f(x;\alpha,\beta) = \frac{x^{\alpha-1} e^{-\beta x} \beta^\alpha}{\Gamma(\alpha)}
$$
$$
\Gamma(\alpha) = (\alpha - 1)! \text{ if } \alpha \in \mathbb{Z} \text{ and } \alpha > 0
$$
Then, if $\mu$ is the mean of your values, and $\sigma^2$ the variance:
$$
\alpha = \frac{\mu^2}{\sigma^2},
\beta = \frac{\mu}{\sigma^2}
$$

This function is implemented as `scipy.stats.gamma` (see https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gamma.html).
Using only the features with a count (`codebook[codebook['type'] == 'count']['variable']`), predict the `is_active` columns. Compare and contrast the following models:
1) Bernoulli naive Bayes
2) Gaussian naive Bayes
3) Gamma naive Bayes (this one you will need to implement yourself!)

In [8]:
# YOUR ANSWER GOES HERE

<a id="4" href="#0" style="text-align: right; display: block;">Back to top</a>

## Part IV

One of the holy grails in drug design is the ability to predict the biological activity of a molecule based on only its structure.
**In all following questions, explain why you perform steps, why you picked specific models, as well as what you conclude from the output.**

1) Train and validate the best model you possibly can to predict the `standard_value` column. Use any and all tricks and techniques you can think of.
2) Are you happy with the resulting model? Is it a good model?

In [9]:
# YOUR ANSWER GOES HERE

***

<a id="X" href="#0" style="text-align: right; display: block;">Back to top</a>

<div class="alert alert-info">

**Note:** After finishing,

1. evaluate the notebook by means of the menu option `Kernel` > `Restart & Run All` and check that your notebook runs without errors;
2. save the evaluated notebook using the menu option `File` > `Save and Checkpoint`;
3. submit your work by clicking on the assignment title in BlackBoard, attaching all your own work (i.e. this notebook plus any required modules; do *not* include the data file), and submitting it;
4. if in doubt, you may check with the exam supervisor that your submission was successfully received;
5. you are free to leave!
    
*Success!*

</div>